spring.application.name=Food ordering

spring.datasource.url=jdbc:mysql://localhost:3306/foodorderapp
spring.datasource.username=root
spring.datasource.password=Santu27070
spring.jpa.hibernate.ddl-auto=update
